/*import Head from "next/head";
import Card from "../components/Card";

const PP = () => {
  return (
    <div>
      <Head>
        <title>Modern Card</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pro.ico" />
      </Head>
      <div class="bg-hero w-screen h-screen bg-cover bg-fixed flex justify-center items-center">
        <Card/>
      </div>
    </div>
  );
}
export default PP;*/

import Profile from "@/components/profile";
import Head from "next/head";
import { useState, useEffect } from "react";
const PP = () => {
  const [follow, setFollow] = useState(false);
  const [message, setMessage] = useState(false);

  const followHandler = () => {
    console.log("Followed");
  };

  const messageHandler = () => {
    console.log("Message");
  };
  return (
 <Profile/>
  );
};
export default PP;
